### ISSUE TITLE
Code Review for Ian

### ISSUE THREAD

**Issue by Samuel787** [AY2122S1-CS2113T-F12-4/tp#145]
Hi @ianwangeen

Generally good code quality.

Here're a suggestion for improvement from me:
1. You can further extract the duty of printing here in `Paser.java` to `Ui.java`
![image](https://user-images.githubusercontent.com/16080561/139531773-3c457b4c-594c-4372-80e6-22e90c07a464.png)

**Comment by ianwangeeen** [comment]
done.
