### ISSUE TITLE
Code Review for Teck Hwee

### ISSUE THREAD

**Issue by Samuel787** [AY2122S1-CS2113T-F12-4/tp#148]
Hi @Teckwhye

Mostly good code quality.

Here're some suggestion(s) to improve your code:

1. In `MemberList.java`, you are throwing exception in the `else` block and then immediately catching it and then re-throwing it. Why do you have to catch the exception here?
![image](https://user-images.githubusercontent.com/16080561/139532411-74152d8d-9421-4637-875b-da61d4ee6900.png)

2. Same comment as (1) here:
![image](https://user-images.githubusercontent.com/16080561/139532458-0d55ee8e-b5dc-4a4e-8fbc-77f7e46cec32.png)

**Comment by xingyuan123** [comment]
can close if settled

**Comment by Teckwhye** [comment]
Solved!
