### ISSUE TITLE
[PE-D] Missing code fence in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-4/tp#192]
The code fence for the expected output in the add feature is missing.
![Screenshot 2021-10-29 at 5.28.47 PM.png](https://raw.githubusercontent.com/shyamgj1900/ped/main/files/f7b49a7a-f8a9-4a81-9c35-291dc4143130.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: shyamgj1900/ped#10

**Comment by ianwangeeen** [comment]
Fixed UG
