### ISSUE TITLE
[PE-D] UI in list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-4/tp#194]
Added multiple spaces in between inputs to test UI. The was no trimming and the list is messy.

![image.png](https://raw.githubusercontent.com/WaiKit-nus/ped/main/files/5fd9b63e-72c8-49cb-976b-a98dd3de53f5.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: WaiKit-nus/ped#9

**Comment by ianwangeeen** [comment]
This should be allowed because the user may want to have certain indentations on his part.
