### ISSUE TITLE
[PE-D] Attendance added for a training session that does not exist

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-4/tp#197]
![image.png](https://raw.githubusercontent.com/edlyIrsyad/ped/main/files/360b4a1c-8d8b-4550-82c2-46ea3a35ec0e.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: edlyIrsyad/ped#8

**Comment by izdiyadfrhn** [comment]
Duplicate of #188
