### ISSUE TITLE
[PE-D] Index out of bounds, wrong exception is thrown

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-4/tp#202]
![Screenshot 2021-10-29 at 5.38.27 PM.png](https://raw.githubusercontent.com/nguyin/ped/main/files/46e8592b-a1a7-46e2-b75a-8fc956fc92cc.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: nguyin/ped#13

**Comment by poppolette** [comment]
This is a mistake on the UG part, it was not clear on the exact syntax.
